/* ============================================================
 * 产品列表 — 模拟数据
 * 说明: 数据结构与 supabase/schema.sql 中的 patterns + skus 表一致
 *       后续接入 Supabase 后替换为真实数据
 * ============================================================ */

/** 颜色色值映射（用于颜色圆点展示） */
export const COLOR_MAP: Record<string, string> = {
  BLK: '#1a1a1a',
  BLU: '#2563eb',
  RED: '#dc2626',
  BRN: '#78350f',
  TAN: '#d2b48c',
  GRN: '#16a34a',
  NAV: '#1e3a5f',
  GRY: '#6b7280',
  WHT: '#f5f5f4',
  PNK: '#ec4899',
  ORG: '#ea580c',
  BGE: '#d4c5a9',
  CML: '#c4956a',
  OLV: '#556b2f',
  WNE: '#722f37',
  CRM: '#fffdd0',
  KHK: '#c3b091',
  LBL: '#93c5fd',
  DBR: '#4a2c0a',
  LPK: '#fbb6ce',
};

/** 颜色代码 → 英文名称 */
export const COLOR_NAME_MAP: Record<string, string> = {
  BLK: 'Black',
  BLU: 'Blue',
  RED: 'Red',
  BRN: 'Brown',
  TAN: 'Tan',
  GRN: 'Green',
  NAV: 'Navy',
  GRY: 'Gray',
  WHT: 'White',
  PNK: 'Pink',
  ORG: 'Orange',
  BGE: 'Beige',
  CML: 'Camel',
  OLV: 'Olive',
  WNE: 'Wine',
  CRM: 'Cream',
  KHK: 'Khaki',
  LBL: 'Light Blue',
  DBR: 'Dark Brown',
  LPK: 'Light Pink',
};

/** 颜色代码 → 中文名称（常用预设，可在添加 SKU 时自动填入） */
export const COLOR_NAME_ZH_MAP: Record<string, string> = {
  BLK: '黑色',
  BLU: '蓝色',
  RED: '红色',
  BRN: '棕色',
  TAN: '卡其棕',
  GRN: '绿色',
  NAV: '藏青色',
  GRY: '灰色',
  WHT: '白色',
  PNK: '粉色',
  ORG: '橙色',
  BGE: '米色',
  CML: '驼色',
  OLV: '军绿色',
  WNE: '酒红色',
  CRM: '奶油色',
  KHK: '卡其色',
  LBL: '浅蓝色',
  DBR: '深棕色',
  LPK: '浅粉色',
};

/** SKU 子项数据 */
export interface SkuItem {
  id: string;
  skuName: string;           // 如 CITYBAG-AP1-BLK（客户提供）
  colorCode: string;         // 颜色代码，如 BLK / #ff5500（客户提供）
  colorNameZh?: string;      // 颜色中文名称，如 黑色（可选，方便内部识别）
  skuCode: string;           // SKU Code 如 SKU001-BLK（客户提供）
  stock: number;             // 库存
  bulkPrice: number;
  dropshipPrice: number;
  status: 'active' | 'discontinued';
  updatedAt: string;
}

/** 产品列表视图数据（Pattern 维度，包含所属 SKU） */
export interface ProductListItem {
  id: string;
  patternCode: string;
  name: string;
  category: string;
  imageUrl: string | null;
  colors: string[];
  bulkPrice: number;
  dropshipPrice: number;
  currency: string;
  packWeight: string;
  packSize: string;
  status: 'active' | 'discontinued';
  createdAt: string;
  skuCount: number;
  skus: SkuItem[];         // SKU 子项列表
}

/** 根据产品信息自动生成 SKU 子项 */
function generateSkus(
  patternCode: string,
  colors: string[],
  skuPrefix: string,
  bulkPrice: number,
  dropshipPrice: number,
): SkuItem[] {
  return colors.map((color) => ({
    id: `${skuPrefix}-${color}`,
    skuName: `${patternCode}-${color}`,
    colorCode: color,
    skuCode: `${skuPrefix}-${color}`,
    stock: Math.floor(Math.random() * 200) + 20,
    bulkPrice,
    dropshipPrice,
    status: 'active' as const,
    updatedAt: '2024/04/12',
  }));
}

/** 模拟产品数据 */
export const MOCK_PRODUCTS: ProductListItem[] = [
  {
    id: 'p001',
    patternCode: 'CITYBAG-AP1',
    name: 'CITY BAG 手提包',
    category: '手袋',
    imageUrl: null,
    colors: ['BLK', 'BRN', 'BGE', 'KHK', 'GRY', 'BLU', 'PNK', 'RED'],
    bulkPrice: 10.20,
    dropshipPrice: 12.00,
    currency: 'USD',
    packWeight: '0.85 kg',
    packSize: '25×18×12 cm',
    status: 'active',
    createdAt: '2024/01/15',
    skuCount: 8,
    skus: generateSkus('CITYBAG-AP1', ['BLK', 'BRN', 'BGE', 'KHK', 'GRY', 'BLU', 'PNK', 'RED'], 'SKU001', 10.20, 12.00),
  },
  {
    id: 'p002',
    patternCode: 'TOTE-2024-02',
    name: 'TOTE 托特包',
    category: '手袋',
    imageUrl: null,
    colors: ['BGE', 'PNK', 'GRN', 'BRN', 'TAN', 'LBL', 'GRY', 'CRM', 'OLV', 'WHT'],
    bulkPrice: 8.40,
    dropshipPrice: 9.80,
    currency: 'USD',
    packWeight: '0.60 kg',
    packSize: '32×28×14 cm',
    status: 'active',
    createdAt: '2024/02/20',
    skuCount: 10,
    skus: generateSkus('TOTE-2024-02', ['BGE', 'PNK', 'GRN', 'BRN', 'TAN', 'LBL', 'GRY', 'CRM', 'OLV', 'WHT'], 'SKU002', 8.40, 9.80),
  },
  {
    id: 'p003',
    patternCode: 'DUFFLE-2024-03',
    name: 'DUFFLE 旅行包',
    category: '手袋',
    imageUrl: null,
    colors: ['GRN', 'BLK', 'NAV', 'BRN', 'TAN', 'ORG', 'GRY'],
    bulkPrice: 11.90,
    dropshipPrice: 13.80,
    currency: 'USD',
    packWeight: '1.20 kg',
    packSize: '45×25×22 cm',
    status: 'active',
    createdAt: '2024/03/05',
    skuCount: 7,
    skus: generateSkus('DUFFLE-2024-03', ['GRN', 'BLK', 'NAV', 'BRN', 'TAN', 'ORG', 'GRY'], 'SKU003', 11.90, 13.80),
  },
  {
    id: 'p004',
    patternCode: 'BACKPACK-2024-04',
    name: 'BACKPACK 双肩包',
    category: '手袋',
    imageUrl: null,
    colors: ['BLK', 'BLU', 'GRN', 'TAN', 'ORG', 'GRY', 'NAV', 'RED', 'CML'],
    bulkPrice: 9.20,
    dropshipPrice: 10.90,
    currency: 'USD',
    packWeight: '0.90 kg',
    packSize: '30×15×45 cm',
    status: 'active',
    createdAt: '2024/03/18',
    skuCount: 9,
    skus: generateSkus('BACKPACK-2024-04', ['BLK', 'BLU', 'GRN', 'TAN', 'ORG', 'GRY', 'NAV', 'RED', 'CML'], 'SKU004', 9.20, 10.90),
  },
  {
    id: 'p005',
    patternCode: 'CROSS-2024-05',
    name: 'CROSS 斜挎包',
    category: '手袋',
    imageUrl: null,
    colors: ['BRN', 'TAN', 'BLK', 'NAV', 'WNE', 'PNK', 'LPK', 'GRY'],
    bulkPrice: 6.80,
    dropshipPrice: 7.90,
    currency: 'USD',
    packWeight: '0.45 kg',
    packSize: '20×15×8 cm',
    status: 'active',
    createdAt: '2024/04/02',
    skuCount: 8,
    skus: generateSkus('CROSS-2024-05', ['BRN', 'TAN', 'BLK', 'NAV', 'WNE', 'PNK', 'LPK', 'GRY'], 'SKU005', 6.80, 7.90),
  },
  {
    id: 'p006',
    patternCode: 'SHOULDER-2024-06',
    name: 'SHOULDER 单肩包',
    category: '手袋',
    imageUrl: null,
    colors: ['LPK', 'RED', 'BLK', 'NAV', 'GRN', 'LBL'],
    bulkPrice: 7.50,
    dropshipPrice: 8.90,
    currency: 'USD',
    packWeight: '0.55 kg',
    packSize: '28×10×18 cm',
    status: 'discontinued',
    createdAt: '2024/04/10',
    skuCount: 6,
    skus: generateSkus('SHOULDER-2024-06', ['LPK', 'RED', 'BLK', 'NAV', 'GRN', 'LBL'], 'SKU006', 7.50, 8.90),
  },
  {
    id: 'p007',
    patternCode: 'WALLET-2024-07',
    name: 'LONG WALLET 长款钱包',
    category: '钱包',
    imageUrl: null,
    colors: ['BLK', 'BRN', 'TAN', 'WNE', 'NAV'],
    bulkPrice: 4.50,
    dropshipPrice: 5.80,
    currency: 'USD',
    packWeight: '0.18 kg',
    packSize: '20×10×3 cm',
    status: 'active',
    createdAt: '2024/04/25',
    skuCount: 5,
    skus: generateSkus('WALLET-2024-07', ['BLK', 'BRN', 'TAN', 'WNE', 'NAV'], 'SKU007', 4.50, 5.80),
  },
  {
    id: 'p008',
    patternCode: 'CARD-2024-08',
    name: 'CARD HOLDER 卡包',
    category: '卡包',
    imageUrl: null,
    colors: ['BLK', 'BRN', 'TAN', 'NAV', 'GRY', 'RED', 'GRN', 'PNK', 'OLV', 'CML', 'WNE', 'BLU'],
    bulkPrice: 2.80,
    dropshipPrice: 3.90,
    currency: 'USD',
    packWeight: '0.08 kg',
    packSize: '11×8×1.5 cm',
    status: 'active',
    createdAt: '2024/05/10',
    skuCount: 12,
    skus: generateSkus('CARD-2024-08', ['BLK', 'BRN', 'TAN', 'NAV', 'GRY', 'RED', 'GRN', 'PNK', 'OLV', 'CML', 'WNE', 'BLU'], 'SKU008', 2.80, 3.90),
  },
  {
    id: 'p009',
    patternCode: 'BELT-2024-09',
    name: 'CLASSIC BELT 经典皮带',
    category: '皮带',
    imageUrl: null,
    colors: ['BLK', 'BRN', 'TAN', 'DBR'],
    bulkPrice: 3.60,
    dropshipPrice: 4.80,
    currency: 'USD',
    packWeight: '0.25 kg',
    packSize: '120×3.5×0.3 cm',
    status: 'active',
    createdAt: '2024/05/20',
    skuCount: 4,
    skus: generateSkus('BELT-2024-09', ['BLK', 'BRN', 'TAN', 'DBR'], 'SKU009', 3.60, 4.80),
  },
  {
    id: 'p010',
    patternCode: 'CLUTCH-2024-10',
    name: 'CLUTCH 手拿包',
    category: '手袋',
    imageUrl: null,
    colors: ['BLK', 'WNE', 'GRY', 'NAV', 'GRN', 'PNK', 'CRM'],
    bulkPrice: 5.20,
    dropshipPrice: 6.50,
    currency: 'USD',
    packWeight: '0.30 kg',
    packSize: '25×15×5 cm',
    status: 'active',
    createdAt: '2024/06/01',
    skuCount: 7,
    skus: generateSkus('CLUTCH-2024-10', ['BLK', 'WNE', 'GRY', 'NAV', 'GRN', 'PNK', 'CRM'], 'SKU010', 5.20, 6.50),
  },
  {
    id: 'p011',
    patternCode: 'MINI-2024-11',
    name: 'MINI BAG 迷你包',
    category: '手袋',
    imageUrl: null,
    colors: ['PNK', 'LBL', 'CRM', 'BLK', 'RED', 'WHT'],
    bulkPrice: 4.80,
    dropshipPrice: 6.20,
    currency: 'USD',
    packWeight: '0.22 kg',
    packSize: '15×10×6 cm',
    status: 'active',
    createdAt: '2024/06/15',
    skuCount: 6,
    skus: generateSkus('MINI-2024-11', ['PNK', 'LBL', 'CRM', 'BLK', 'RED', 'WHT'], 'SKU011', 4.80, 6.20),
  },
  {
    id: 'p012',
    patternCode: 'BRIEFCASE-2024-12',
    name: 'BRIEFCASE 公文包',
    category: '手袋',
    imageUrl: null,
    colors: ['BLK', 'BRN', 'NAV'],
    bulkPrice: 15.80,
    dropshipPrice: 18.50,
    currency: 'USD',
    packWeight: '1.50 kg',
    packSize: '40×30×10 cm',
    status: 'active',
    createdAt: '2024/07/01',
    skuCount: 3,
    skus: generateSkus('BRIEFCASE-2024-12', ['BLK', 'BRN', 'NAV'], 'SKU012', 15.80, 18.50),
  },
  {
    id: 'p013',
    patternCode: 'COINPURSE-2024-13',
    name: 'COIN PURSE 零钱包',
    category: '钱包',
    imageUrl: null,
    colors: ['BLK', 'BRN', 'TAN', 'PNK', 'LBL', 'RED', 'GRN', 'ORG'],
    bulkPrice: 1.80,
    dropshipPrice: 2.50,
    currency: 'USD',
    packWeight: '0.05 kg',
    packSize: '10×8×2 cm',
    status: 'active',
    createdAt: '2024/07/20',
    skuCount: 8,
    skus: generateSkus('COINPURSE-2024-13', ['BLK', 'BRN', 'TAN', 'PNK', 'LBL', 'RED', 'GRN', 'ORG'], 'SKU013', 1.80, 2.50),
  },
  {
    id: 'p014',
    patternCode: 'WEEKENDER-2024-14',
    name: 'WEEKENDER 周末旅行包',
    category: '手袋',
    imageUrl: null,
    colors: ['BLK', 'BRN', 'KHK', 'OLV', 'NAV'],
    bulkPrice: 18.50,
    dropshipPrice: 22.00,
    currency: 'USD',
    packWeight: '1.80 kg',
    packSize: '55×30×25 cm',
    status: 'active',
    createdAt: '2024/08/05',
    skuCount: 5,
    skus: generateSkus('WEEKENDER-2024-14', ['BLK', 'BRN', 'KHK', 'OLV', 'NAV'], 'SKU014', 18.50, 22.00),
  },
  {
    id: 'p015',
    patternCode: 'POUCH-2024-15',
    name: 'POUCH 收纳袋',
    category: '其他',
    imageUrl: null,
    colors: ['BLK', 'TAN', 'GRY', 'NAV', 'OLV', 'BRN'],
    bulkPrice: 3.20,
    dropshipPrice: 4.50,
    currency: 'USD',
    packWeight: '0.12 kg',
    packSize: '22×14×5 cm',
    status: 'active',
    createdAt: '2024/08/18',
    skuCount: 6,
    skus: generateSkus('POUCH-2024-15', ['BLK', 'TAN', 'GRY', 'NAV', 'OLV', 'BRN'], 'SKU015', 3.20, 4.50),
  },
  {
    id: 'p016',
    patternCode: 'KEYHOLDER-2024-16',
    name: 'KEY HOLDER 钥匙包',
    category: '其他',
    imageUrl: null,
    colors: ['BLK', 'BRN', 'TAN', 'RED'],
    bulkPrice: 2.20,
    dropshipPrice: 3.10,
    currency: 'USD',
    packWeight: '0.06 kg',
    packSize: '12×7×2 cm',
    status: 'active',
    createdAt: '2024/09/01',
    skuCount: 4,
    skus: generateSkus('KEYHOLDER-2024-16', ['BLK', 'BRN', 'TAN', 'RED'], 'SKU016', 2.20, 3.10),
  },
  {
    id: 'p017',
    patternCode: 'PASSPORT-2024-17',
    name: 'PASSPORT HOLDER 护照包',
    category: '其他',
    imageUrl: null,
    colors: ['BLK', 'BRN', 'NAV', 'WNE', 'TAN', 'GRY', 'GRN'],
    bulkPrice: 3.80,
    dropshipPrice: 5.00,
    currency: 'USD',
    packWeight: '0.10 kg',
    packSize: '14×10×1.5 cm',
    status: 'active',
    createdAt: '2024/09/15',
    skuCount: 7,
    skus: generateSkus('PASSPORT-2024-17', ['BLK', 'BRN', 'NAV', 'WNE', 'TAN', 'GRY', 'GRN'], 'SKU017', 3.80, 5.00),
  },
  {
    id: 'p018',
    patternCode: 'BUCKET-2024-18',
    name: 'BUCKET BAG 水桶包',
    category: '手袋',
    imageUrl: null,
    colors: ['BLK', 'CML', 'TAN', 'WNE', 'GRN', 'NAV', 'BRN', 'GRY'],
    bulkPrice: 8.90,
    dropshipPrice: 10.50,
    currency: 'USD',
    packWeight: '0.65 kg',
    packSize: '22×22×28 cm',
    status: 'active',
    createdAt: '2024/10/01',
    skuCount: 8,
    skus: generateSkus('BUCKET-2024-18', ['BLK', 'CML', 'TAN', 'WNE', 'GRN', 'NAV', 'BRN', 'GRY'], 'SKU018', 8.90, 10.50),
  },
  {
    id: 'p019',
    patternCode: 'SATCHEL-2024-19',
    name: 'SATCHEL 剑桥包',
    category: '手袋',
    imageUrl: null,
    colors: ['BRN', 'BLK', 'TAN', 'WNE', 'NAV'],
    bulkPrice: 9.80,
    dropshipPrice: 11.50,
    currency: 'USD',
    packWeight: '0.75 kg',
    packSize: '28×20×10 cm',
    status: 'active',
    createdAt: '2024/10/20',
    skuCount: 5,
    skus: generateSkus('SATCHEL-2024-19', ['BRN', 'BLK', 'TAN', 'WNE', 'NAV'], 'SKU019', 9.80, 11.50),
  },
  {
    id: 'p020',
    patternCode: 'ZIPWALLET-2024-20',
    name: 'ZIP WALLET 拉链钱包',
    category: '钱包',
    imageUrl: null,
    colors: ['BLK', 'BRN', 'PNK', 'NAV', 'RED', 'TAN', 'GRY', 'WNE', 'CML'],
    bulkPrice: 5.60,
    dropshipPrice: 7.20,
    currency: 'USD',
    packWeight: '0.20 kg',
    packSize: '19×10×2.5 cm',
    status: 'active',
    createdAt: '2024/11/05',
    skuCount: 9,
    skus: generateSkus('ZIPWALLET-2024-20', ['BLK', 'BRN', 'PNK', 'NAV', 'RED', 'TAN', 'GRY', 'WNE', 'CML'], 'SKU020', 5.60, 7.20),
  },
  {
    id: 'p021',
    patternCode: 'HOBO-2024-21',
    name: 'HOBO BAG 半月包',
    category: '手袋',
    imageUrl: null,
    colors: ['BLK', 'CML', 'TAN', 'GRY', 'BRN'],
    bulkPrice: 8.20,
    dropshipPrice: 9.80,
    currency: 'USD',
    packWeight: '0.55 kg',
    packSize: '35×25×12 cm',
    status: 'discontinued',
    createdAt: '2024/11/20',
    skuCount: 5,
    skus: generateSkus('HOBO-2024-21', ['BLK', 'CML', 'TAN', 'GRY', 'BRN'], 'SKU021', 8.20, 9.80),
  },
  {
    id: 'p022',
    patternCode: 'FANNY-2024-22',
    name: 'FANNY PACK 腰包',
    category: '手袋',
    imageUrl: null,
    colors: ['BLK', 'GRN', 'NAV', 'ORG', 'GRY', 'KHK'],
    bulkPrice: 5.80,
    dropshipPrice: 7.50,
    currency: 'USD',
    packWeight: '0.28 kg',
    packSize: '30×14×8 cm',
    status: 'active',
    createdAt: '2024/12/01',
    skuCount: 6,
    skus: generateSkus('FANNY-2024-22', ['BLK', 'GRN', 'NAV', 'ORG', 'GRY', 'KHK'], 'SKU022', 5.80, 7.50),
  },
  {
    id: 'p023',
    patternCode: 'WRISTLET-2024-23',
    name: 'WRISTLET 手腕包',
    category: '手袋',
    imageUrl: null,
    colors: ['BLK', 'PNK', 'LBL', 'CRM', 'RED'],
    bulkPrice: 3.50,
    dropshipPrice: 4.80,
    currency: 'USD',
    packWeight: '0.15 kg',
    packSize: '20×12×4 cm',
    status: 'active',
    createdAt: '2024/12/15',
    skuCount: 5,
    skus: generateSkus('WRISTLET-2024-23', ['BLK', 'PNK', 'LBL', 'CRM', 'RED'], 'SKU023', 3.50, 4.80),
  },
  {
    id: 'p024',
    patternCode: 'LAPTOP-2025-01',
    name: 'LAPTOP SLEEVE 电脑包',
    category: '其他',
    imageUrl: null,
    colors: ['BLK', 'GRY', 'NAV', 'BRN'],
    bulkPrice: 6.50,
    dropshipPrice: 8.00,
    currency: 'USD',
    packWeight: '0.35 kg',
    packSize: '36×26×2 cm',
    status: 'active',
    createdAt: '2025/01/10',
    skuCount: 4,
    skus: generateSkus('LAPTOP-2025-01', ['BLK', 'GRY', 'NAV', 'BRN'], 'SKU024', 6.50, 8.00),
  },
  {
    id: 'p025',
    patternCode: 'TRAVEL-2025-02',
    name: 'TRAVEL SET 旅行套装',
    category: '其他',
    imageUrl: null,
    colors: ['BLK', 'BRN', 'TAN'],
    bulkPrice: 22.00,
    dropshipPrice: 26.00,
    currency: 'USD',
    packWeight: '2.00 kg',
    packSize: '50×35×20 cm',
    status: 'active',
    createdAt: '2025/02/01',
    skuCount: 3,
    skus: generateSkus('TRAVEL-2025-02', ['BLK', 'BRN', 'TAN'], 'SKU025', 22.00, 26.00),
  },
];

/** 所有分类选项 */
export const CATEGORY_OPTIONS = ['全部', '手袋', '钱包', '皮带', '卡包', '其他'] as const;

/** 所有状态选项 */
export const STATUS_OPTIONS = ['全部状态', '启用', '停用'] as const;
